### ISSUE TITLE
Wallet address is missing in UI

### ISSUE THREAD

**Issue by slinlee** [slavingia/fweb3.xyz#150] opened 2022-03-03 18:57 UTC
After @jester7 's pr, the wallet address is missing if I visit the website fweb3.xyz with my own wallet connected via metamask. (I don't have a .eth name)

![image](https://user-images.githubusercontent.com/1197406/156633204-e2d18185-12b5-4b30-a773-bbb7b1c31700.png)

**Comment by slavingia** [comment] 2022-03-03 19:07
oops. hm.

**Comment by jester7** [comment] 2022-03-03 19:18
Sorry about that, I think this is an easy fix. Will look at it later today.

**Comment by jester7** [comment] 2022-03-04 04:20
Hey @slinlee and @slavingia, I can't remember where on the main page the wallet address would show for connected wallets that have already won (when not verifying, just on the main page).

The regression I inadvertently introduced was to omit the "You" in the h2 tag above the main section.

I fixed it so it does say "You learned and built in web3!" when not verifying, and the wallet address or ens name if verifying somebody else.

I'm working on some other small tweaks related to displaying of wallet addresses on main page and verification page before submitting PR. Will comment in discord for feedback from others.

**Comment by jester7** [comment] 2022-03-04 04:49
Thinking about doing this for the verification page:
![image](https://user-images.githubusercontent.com/1183817/156700580-7e95d01e-c4a0-4231-8eaa-3bb560188abb.png)

And this to main page:
![image](https://user-images.githubusercontent.com/1183817/156701315-8471c25b-13a2-4007-865e-51126ffc9dd5.png)

**Comment by jester7** [comment] 2022-03-07 02:36
Fixed in #155 . Actually in that spot I don't think it had a wallet address, it should say just "You learned and built in web3!" as it did before. Was missing "You" because of an improper placement of ENSLookup tag.

**Comment by jester7** [comment] 2022-03-07 05:30
Closed PR and resubmitted, now #156  due to improper merge on my end before submitting previous pr.

**Closed** 2022-03-07 22:36 UTC
